name: Golang and Code Repo setup, reusable workflow
description: "Checks out the repo and sets up golang"
runs:
  using: "composite"
  steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3

