name: CI

on:
  pull_request:

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Go and Code Repo setup
        uses: ./github/workflows/go-setup.yml

      - name: Fmt
        run: make fmt

  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - name: Go and Code Repo setup
        uses: ./github/workflows/go-setup.yml

      - name: Vet
        run: make vet

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Go and Code Repo setup
        uses: ./github/workflows/go-setup.yml

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Go and Code Repo setup
        uses: ./github/workflows/go-setup.yml

      - name: Test
        run: make test

